### PR TITLE
Add a DVS eye tracking dataset from the paper 3ET

### PR DESCRIPTION
**Pull request by ZuowenWang0000**
The new tonic/datasets/threeET_eyetracking.py provides a new dataset from the paper 3ET: Efficient Event-based Eye Tracking using a Change-Based ConvLSTM Network (https://arxiv.org/pdf/2308.11771.pdf)

Thanks for maintaining this wonderful DVS dataset library.

### CODE REVIEW

**Comment by ZuowenWang0000** [comment]
Hi Gregor thanks for checking!
For the test files could you upload the attached two files (zipped) into a folder in your base_url?

thanks again!
[testcase.zip](https://github.com/neuromorphs/tonic/files/13705559/testcase.zip)

**Comment by ZuowenWang0000** [comment]
hello Gregor,
thanks for your info! I have added the entry to the documentation and I made a test case for the loader. Could you help unzip and upload these two files under a folder? 
thanks again!

[testcase.zip](https://github.com/neuromorphs/tonic/files/13712545/testcase.zip)

**Comment by biphasic** [comment]
perfect, thanks a lot. Here are the links to the two uploaded files:
testcase.txt https://nextcloud.lenzgregor.com/s/G6ejNmXNnB2sKyc
testcase.h5 https://nextcloud.lenzgregor.com/s/4aiA4BAqz5km4Gc

**Comment by biphasic** [comment]
this looks great now! Nicely done. Are you happy for me to merge?

**Comment by ZuowenWang0000** [comment]
yes please merge. thanks!

**Pull request merged**
