### PR TITLE
Main

### PR DESCRIPTION
**Pull request by gokulbnr**
This has not been tested meticulously. Has worked for me so far. The changes include:
1. Added a returned value in read_aedat_header_from_file() function that returns the system time (using System.currentTimeMillis on jAER: https://github.com/SensorsINI/jaer) to obtain timestamps that can be used to synchronize with data from other modules. This had to be done because the timestamps I was otherwise getting were based on System.nanoTime() (java) on jAER which are not exactly representative of the absolute system time. (ref: top answer in https://stackoverflow.com/questions/8756982/how-to-get-the-microseconds-from-a-date)
2. Made necessary changes in read_davis_346() to collect the absolute timestamp returned in the above-mentioned function and return downstream to be used wherever necessary by the user. 
I'm not sure if this breaks anything for the rest of the functions though. I noticed read_aedat_header_from_file() is called by several other functions that I haven't touched or checked in due course of this commit.

### CODE REVIEW

**Comment by biphasic** [comment]
Hey @gokulbnr , thanks for that. Let's see if the tests pass, shall we? But first, could you please point your pull request to the development branch of Tonic and not the main. Second, it says that there are merge conflicts, please resolve them as well. Then the automated test can start

**Comment by gokulbnr** [comment]
Ah, this was expected I suppose. Would you like me to take a look at them?

**Comment by biphasic** [comment]
yes, this should be a rather easy fix in the tests
```
    def test_read_aedat_events():
>       data_version, data_start = tonic.io.read_aedat_header_from_file(
            "test/test_data/sample.aedat4"
        )
E       ValueError: too many values to unpack (expected 2)
```

**Comment by gokulbnr** [comment]
Hi @biphasic
I don't understand what the above pytest fail's about. Could you please point me to what that's about?

**Comment by fabrizio-ottati** [comment]
It seems that only the documentation test is failing! I will look at your commit tomorrow :)

**Comment by biphasic** [comment]
Hello, the issue with the documentation was upstream https://github.com/readthedocs/sphinx-autoapi/issues/407 but I [pinned](https://github.com/neuromorphs/tonic/commit/2626e31cbc756f6ec9615e04f1173268112c093d) the problematic package to an earlier version in the develop branch, where the documentation [builds](https://github.com/neuromorphs/tonic/actions/runs/6544798580) now. Will merge this

**Pull request merged**
