### PR TITLE
functions returns a list of absolute timestamps instead of returning …

### PR DESCRIPTION
**Pull request by gokulbnr**
In my previous commit, absolute system time at the beginning of the aedat (from its header) was being returned separately. Have fused that with the list of timestamps now. This ensures that the returned timestamps list (as a part of the structures array) is the absolute system time. This may help make the data more easy to synchronize with other data sequences.

### CODE REVIEW

**Comment by biphasic** [comment]
hey @gokulbnr , my preference normally is to provide the raw data as is, to leave it up to the user to modify it if they want to. There might be a certain start timestamp that a user wants to synchronise to, and subtracting that before returning it will make that impossible. One other option that I can think of is an extra parameter

**Comment by biphasic** [comment]
also, I fixed the test in the develop branch

**Comment by gokulbnr** [comment]
Hi @biphasic, thanks for taking a look! Yes, it does make sense to let the user decide how to utilize the raw data. Thanks for keeping me in the loop on this!

**Comment by biphasic** [comment]
would you like to change this or should I close it?

**Comment by gokulbnr** [comment]
The code before the above commits aligns with the philosophy of returning the relative and absolute timestamps. 
I have a few other changes coming up, but they are not related to the timestamps. So this request can be closed.

**Pull request closed without merging**
